### ISSUE TITLE
[Mapa PA] Implementar obrigatoriedade nos campos do cadastro dos Agente Individuais

### ISSUE THREAD

**Issue by daphnemartinsba** [hacklabr/mapas-PA#3]
- Os campos obrigatórios devem conter um asterisco vermelho indicando sua obrigatoriedade, tal qual o asterisco da área de atuação: 
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/997da997-1075-427a-aad3-7d49f2b6c9ef)

- Quando o campo não for preenchido, ao tentar salvar as alterações no Agente Individual, deve ser emitido um erro avisando que falta o preenchimento dos campos. Da mesma forma que ocorre quando não se preenche a descrição curta:
![image.png](https://images.zenhubusercontent.com/62309d85d1e1c3b51b7902da/f26644ba-92ce-49b6-be50-b6bd78e8954b)

Deixar obrigatório o preenchimento dos seguintes campos de cadastro do bloco de dados pessoais: 

- [x] Nome Completo, 

- [x] CPF/CNPJ, 

- [x] Email, 

- [x] Telefone, 

- [x] Município e Estado

Deixar obrigatório o preenchimento dos seguintes campos de cadastro do bloco de dados pessoais sensíveis: 

- [x] Gênero (Mulher cis, Homem cis, Outros), 

- [x] Raça/Cor.

**Comment by erleibiazzio** [comment]
Copiar  arquivo   `src/protected/application/conf/agent-types.php`  para o ambiente MapasBr e definir os campos abaixo como obrigatório

 - En_Município
 - En_Estado
