### ISSUE TITLE
Publicação  BI - Metabase 

### ISSUE THREAD

**Issue by erleibiazzio** [hacklabr/mapas-PA#7]
- [ ]  Criar domínio e publicar ambiente em produção
- [x] Ajustar links públicos

**Comment by daphnemartinsba** [comment]
Links Públicos:
	- Eventos: https://bi.mapacultural.pa.gov.br/public/dashboard/1bfdba17-1340-4ca9-9bc6-ab7dde8c8503
	- Espaços: https://bi.mapacultural.pa.gov.br/public/dashboard/7eb10b1d-43f3-4adf-aabc-fa46bdd0073a
	- Agentes Individuais: https://bi.mapacultural.pa.gov.br/public/dashboard/dbf9eb35-9304-49a5-9c63-646687bdde41
	- Oportunidades e Inscrições: https://bi.mapacultural.pa.gov.br/public/dashboard/39ce65ee-9d2b-432e-b9d2-e688b18ece7d
	- Agentes Coletivos: https://bi.mapacultural.pa.gov.br/public/dashboard/58913ac8-d511-41e6-887c-4647d98f71e7
	- Projetos: https://bi.mapacultural.pa.gov.br/public/dashboard/6fe335cd-0f63-4ad6-95df-315c137e82e0
	- Geral de usuários: https://bi.mapacultural.pa.gov.br/public/dashboard/bdb52e6a-d225-4ad2-8f53-b3e81a8cbfb3
	- Geral de entidades: https://bi.mapacultural.pa.gov.br/public/dashboard/0d35b260-7c5b-4f19-8c52-10408eccee16
